spring:
  application:
    name: jago-config-server
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/ssidibe/jago-config-repos
          uri: file:///usr/local/jago-config-repos
          clone-on-start: true
  profiles:
    active: ${SERVEUR_PROFILE:prod}
server:
  port: 80
