spring:
  application:
    name: jago-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/ssidibe/formation_ml/jago-config-repos
          clone-on-start: true
server:
  port: 80

